### ISSUE TITLE
如何将eval.sh运行起来呢？

### ISSUE THREAD

**Issue by S-GeGe** [PANXiao1994/mRASP2#17]
如何将eval.sh运行起来呢？求指导一下 @PANXiao1994

**Comment by PANXiao1994** [comment]
你好。请问是在哪遇到了问题。What difficulties do you have? Please detail them.

**Comment by S-GeGe** [comment]
- **我使用的master分支的代码，执行eval.sh的部分代码，代码如下【这么做的原因是，个人的想法是单独去测试模型的效果，根据infer_test()所需的参数，去给定它。】：**

```
# 执行的代码脚本
repo_dir=~/mRASP2
test_path=~/mRASP2/evaltest/data/binarized/en_de/en2de/wmt14【这里是en2de的data-bin文件，【沿用的mrasp的】】
model_dir=~/mRASP2/evaltest/model/pretrain【这里我放的是12e12d的模型】
gpu=1
final_res_file=~/sungege/mRASP2/evaltest/model/evaltest/orig.txt
src=en
tgt=de
infer_test () {
    test_path=$1
    ckpts=$2
    gpu=$3
    final_res_file=$4
    src=$5
    tgt=$6
    gpu_cmd="CUDA_VISIBLE_DEVICES=$gpu "
    lang_token="LANG_TOK_"`echo "${tgt} " | tr '[a-z]' '[A-Z]'`
    [[ -z ${max_source_positions} ]] && max_source_positions=1024
    [[ -z ${max_target_positions} ]] && max_target_positions=1024
    command=${gpu_cmd}"fairseq-generate ${test_path} \
    --user-dir ${repo_dir}/mcolt \
    -s ${src} \
    -t ${tgt} \
    --skip-invalid-size-inputs-valid-test \
    --path ${ckpts} \
    --max-tokens 1024 \
    --task translation_w_langtok \
    ${options} \
    --lang-prefix-tok ${lang_token} \
    --max-source-positions ${max_source_positions} \
    --max-target-positions ${max_target_positions} \
    --nbest 1 | grep -E '[S|H|P|T]-[0-9]+' > ${final_res_file}
    "
    echo "$command"
}
command=`infer_test ${test_path} ${model_dir}/checkpoint_last.pt ${gpu} ${final_res_file} ${src} ${tgt}`
echo "${command}"
eval $command &
```

- ** 执行后报错【fairseq版本为0.10.2】： **

```
Traceback (most recent call last):
  File "/data1/home/nmt/anaconda3/envs/fairseq10_1/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "/data1/home/nmt/sungege/fairseq/fairseq_cli/generate.py", line 379, in cli_main
    main(args)
  File "/data1/home/nmt/sungege/fairseq/fairseq_cli/generate.py", line 41, in main
    return _main(args, sys.stdout)
  File "/data1/home/nmt/sungege/fairseq/fairseq_cli/generate.py", line 94, in _main
    num_shards=args.checkpoint_shard_count,
  File "/data1/home/nmt/sungege/fairseq/fairseq/checkpoint_utils.py", line 256, in load_model_ensemble
    num_shards,
  File "/data1/home/nmt/sungege/fairseq/fairseq/checkpoint_utils.py", line 279, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/data1/home/nmt/sungege/fairseq/fairseq/checkpoint_utils.py", line 232, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/data1/home/nmt/sungege/fairseq/fairseq/checkpoint_utils.py", line 420, in _upgrade_state_dict
    state["args"].task = "translation"
AttributeError: 'NoneType' object has no attribute 'task'
```

- **更换了几个fairseq的其它版本，依旧有这个错误，但是使用fairseq0.10.1和fairseq0.10.0时报错前加载了一部分模型的信息，具体如下：**

```
 INFO | fairseq_cli.generate | Namespace(all_gather_list_size=16384, batch_size=None, batch_size_valid=None, beam=5, bf16=False, bpe=None, broadcast_buffers=False, bucket_cap_mb=25, checkpoint_shard_count=1, checkpoint_suffix='', constraints=None, cpu=False, criterion='cross_entropy', curriculum=0, data='/data1/home/nmt/sungege/mRASP2/evaltest/data/binarized/en_de/en2de/wmt14', data_buffer_size=10, dataset_impl=None, ddp_backend='c10d', decoding_format=None, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=1, distributed_wrapper='DDP', diverse_beam_groups=-1, diverse_beam_strength=0.5, diversity_rate=-1.0, empty_cache_freq=0, eval_bleu=False, eval_bleu_args=None, eval_bleu_detok='space', eval_bleu_detok_args=None, eval_bleu_print_samples=False, eval_bleu_remove_bpe=None, eval_tokenized_bleu=False, fast_stat_sync=False, find_unused_parameters=False, fix_batches_to_gpus=False, fixed_validation_seed=None, force_anneal=None, fp16=False, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, gen_subset='test', iter_decode_eos_penalty=0.0, iter_decode_force_max_iter=False, iter_decode_max_iter=10, iter_decode_with_beam=1, iter_decode_with_external_reranker=False, lang_prefix_tok='LANG_TOK_DE', left_pad_source='True', left_pad_target='False', lenpen=1, lm_path=None, lm_weight=0.0, load_alignments=False, localsgd_frequency=3, log_format=None, log_interval=100, lr_scheduler='fixed', lr_shrink=0.1, match_source_len=False, max_len_a=0, max_len_b=200, max_source_positions=1024, max_target_positions=1024, max_tokens=1024, max_tokens_valid=1024, memory_efficient_bf16=False, memory_efficient_fp16=False, min_len=1, min_loss_scale=0.0001, model_overrides='{}', model_parallel_size=1, nbest=1, no_beamable_mm=False, no_early_stop=False, no_progress_bar=False, no_repeat_ngram_size=0, no_seed_provided=False, nprocs_per_node=1, num_batch_buckets=0, num_shards=1, num_workers=1, optimizer=None, path='/data1/home/nmt/sungege/mRASP2/evaltest/model/pretrain/checkpoint_last.pt', pipeline_balance=None, pipeline_checkpoint='never', pipeline_chunks=0, pipeline_decoder_balance=None, pipeline_decoder_devices=None, pipeline_devices=None, pipeline_encoder_balance=None, pipeline_encoder_devices=None, pipeline_model_parallel=False, prefix_size=0, print_alignment=False, print_step=False, profile=False, quantization_config_path=None, quiet=False, remove_bpe=None, replace_unk=None, required_batch_size_multiple=8, required_seq_len_multiple=1, results_path=None, retain_dropout=False, retain_dropout_modules=None, retain_iter_history=False, sacrebleu=False, sampling=False, sampling_topk=-1, sampling_topp=-1.0, score_reference=False, scoring='bleu', seed=1, shard_id=0, skip_invalid_size_inputs_valid_test=True, slowmo_algorithm='LocalSGD', slowmo_momentum=None, source_lang='en', target_lang='de', task='translation_w_langtok', temperature=1.0, tensorboard_logdir=None, threshold_loss_scale=None, tokenizer=None, tpu=False, train_subset='train', truncate_source=False, unkpen=0, unnormalized=False, upsample_primary=1, user_dir='/data1/home/nmt/sungege/mRASP2/mcolt', valid_subset='valid', validate_after_updates=0, validate_interval=1, validate_interval_updates=0, warmup_updates=0, zero_sharding='none')
2022-01-10 10:46:07 | INFO | mcolt.tasks.translation_w_langtok | [en] dictionary: 64871 types
2022-01-10 10:46:07 | INFO | mcolt.tasks.translation_w_langtok | [de] dictionary: 64871 types
2022-01-10 10:46:07 | INFO | fairseq.data.data_utils | loaded 100 examples from: /data1/home/nmt/sungege/mRASP2/evaltest/data/binarized/en_de/en2de/wmt14/test.en-de.en
2022-01-10 10:46:07 | INFO | fairseq.data.data_utils | loaded 100 examples from: /data1/home/nmt/sungege/mRASP2/evaltest/data/binarized/en_de/en2de/wmt14/test.en-de.de
2022-01-10 10:46:07 | INFO | mcolt.tasks.translation_w_langtok | /data1/home/nmt/sungege/mRASP2/evaltest/data/binarized/en_de/en2de/wmt14 test en-de 100 examples
2022-01-10 10:46:07 | INFO | fairseq_cli.generate | loading model(s) from /data1/home/nmt/sungege/mRASP2/evaltest/model/pretrain/checkpoint_last.pt
Traceback (most recent call last):
  File "/data1/home/nmt/anaconda3/envs/fairseq10.1/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "/data1/home/nmt/sungege/fairseq/fairseq_cli/generate.py", line 379, in cli_main
    main(args)
  File "/data1/home/nmt/sungege/fairseq/fairseq_cli/generate.py", line 41, in main
    return _main(args, sys.stdout)
  File "/data1/home/nmt/sungege/fairseq/fairseq_cli/generate.py", line 94, in _main
    num_shards=args.checkpoint_shard_count,
  File "/data1/home/nmt/sungege/fairseq/fairseq/checkpoint_utils.py", line 256, in load_model_ensemble
    num_shards,
  File "/data1/home/nmt/sungege/fairseq/fairseq/checkpoint_utils.py", line 279, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/data1/home/nmt/sungege/fairseq/fairseq/checkpoint_utils.py", line 232, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/data1/home/nmt/sungege/fairseq/fairseq/checkpoint_utils.py", line 420, in _upgrade_state_dict
    state["args"].task = "translation"
AttributeError: 'NoneType' object has no attribute 'task'
```
请问这个错误还是版本的问题吗？ 我已将fairseq0.9.0至fairseq0.10.2都试了一次，或是我的想法不对，不能这样进行eval.sh的执行，那要如何才能执行起来呢？

@PANXiao1994

**Comment by TheHonestBob** [comment]
> 如何将eval.sh运行起来呢？求指导一下 @PANXiao1994

我也是遇到这个问题，请问你是如何解决的，我看了一下，主要原因是开源的3个模型文件中args为空，mrasp中的args不是空的，是保存模型是出错了，还是fairseq新版本不需要args

**Comment by PANXiao1994** [comment]
是版本不同导致的，可以写脚本转换一下ckptSent from my iPhoneOn Jun 6, 2023, at 8:27 PM, TheHonestBob ***@***.***> wrote:﻿

如何将eval.sh运行起来呢？求指导一下 @PANXiao1994

我也是遇到这个问题，请问你是如何解决的，我看了一下，主要原因是开源的3个模型文件中args为空，mrasp中的args不是空的，是保存模型是出错了，还是fairseq新版本不需要args

**Comment by TheHonestBob** [comment]
> 是版本不同导致的，可以写脚本转换一下ckptSent from my iPhoneOn Jun 6, 2023, at 8:27 PM, TheHonestBob ***@***.***> wrote:﻿ 如何将eval.sh运行起来呢？求指导一下 @PANXiao1994 我也是遇到这个问题，请问你是如何解决的，我看了一下，主要原因是开源的3个模型文件中args为空，mrasp中的args不是空的，是保存模型是出错了，还是fairseq新版本不需要args —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
感谢，我刚才去fairseq搜索了一下，使用0.12.2版本就可以了

**Comment by Sen-Ran** [comment]
> > 是版本不同导致的，可以写脚本转换一下ckptSent from my iPhoneOn Jun 6, 2023, at 8:27 PM, TheHonestBob _**@**_._**> wrote:﻿ 如何将eval.sh运行起来呢？求指导一下 @PANXiao1994 我也是遇到这个问题，请问你是如何解决的，我看了一下，主要原因是开源的3个模型文件中args为空，mrasp中的args不是空的，是保存模型是出错了，还是fairseq新版本不需要args —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: _**@**_.**_>
> > 感谢，我刚才去fairseq搜索了一下，使用0.12.2版本就可以了

你好，想请问一下你的eval的数据使用的是哪一个呢？

**Comment by TheHonestBob** [comment]
> > > 是版本不同导致的，可以写脚本转换一下ckptSent from my iPhoneOn Jun 6, 2023, at 8:27 PM, TheHonestBob _**@**_._**> wrote:﻿ 如何将eval.sh运行起来呢？求指导一下 @PANXiao1994 我也是遇到这个问题，请问你是如何解决的，我看了一下，主要原因是开源的3个模型文件中args为空，mrasp中的args不是空的，是保存模型是出错了，还是fairseq新版本不需要args —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: _**@**_.**_>
> > > 感谢，我刚才去fairseq搜索了一下，使用0.12.2版本就可以了
> 
> 你好，想请问一下你的eval的数据使用的是哪一个呢？

不太记得，如果你会使用transformers库的话，我已经将mrasp2的模型权重改为了transformers库直接调用的方式，https://huggingface.co/ENLP/mrasp2

**Comment by Sen-Ran** [comment]
> > > > 是版本不同导致的，可以写脚本转换一下ckptSent from my iPhoneOn Jun 6, 2023, at 8:27 PM, TheHonestBob _**@**_._**> wrote:﻿ 如何将eval.sh运行起来呢？求指导一下 @PANXiao1994 我也是遇到这个问题，请问你是如何解决的，我看了一下，主要原因是开源的3个模型文件中args为空，mrasp中的args不是空的，是保存模型是出错了，还是fairseq新版本不需要args —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: _**@**_.**_>
> > > > 感谢，我刚才去fairseq搜索了一下，使用0.12.2版本就可以了
> > 
> > 
> > 你好，想请问一下你的eval的数据使用的是哪一个呢？
> 
> 不太记得，如果你会使用transformers库的话，我已经将mrasp2的模型权重改为了transformers库直接调用的方式，https://huggingface.co/ENLP/mrasp2

非常感谢您的回复，我在CSDN上给您发了私信，如果您方便的话，麻烦您看一下。
